<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;

class LoginType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        #parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add('_username', TextType::class,[
                'attr'          => ['class' => 'user_name', 'placeholder' => 'Username'],
                'required'      =>false,
                'constraints'   => [
                    new NotBlank(['message' => 'Bitte geben Sie Ihren Benutzernamen ein.']),
                ],
            ])
            ->add('_password', PasswordType::class,[
                'attr'          => ['class' => 'pass', 'placeholder' => 'Password'],
                'required'      =>false,
                'constraints'   => [
                    new NotBlank(['message' => 'Bitte geben Sie Ihr Passwort ein.']),
                    new Length([
                        'min'       => 8,
                        'max'       => 20,
                        'minMessage'=> "Der Passwort muss mindestens {{ limit }} Zeichen lang sein_.",
                        'maxMessage'=> "Der Passwort muss maximal {{ limit }} Zeichen lang sein.",
                        ]),
                ],
            ]);

//            ->add('login', SubmitType::class,['label'=>'Login']);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'csrf-protection'   => true, // Standardmäßig true, aber zur Sicherheit hier hinzufügen
            'csrf_field_name'   => '_csrf_token', // Der Name des CSRF-Feldes (muss genau '_csrf_token' schreiben ??)
            'csrf_token_id'     => 'authenticate', // Ein eindeutiger Bezeichner für das Token
            'last_username'     => null, // Default value for last username
        ]);
    }

    // this function change the name of form --> if not create this function and return to ''
    // form has a name and the children-name always begin with form-name ex: formName_[childName]
    public function getBlockPrefix(): string
    {
        return ''; // Set your custom form name here
    }
}
