<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SignupType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        #parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add('name', TextType::class,[
                'attr'      => ['class' => 'name', 'placeholder' => 'Name'],
                'required'  =>false,
            ])
            ->add('username', TextType::class,[
                'attr'      => ['class' => 'user_name', 'placeholder' => 'Username'],
                'required'  =>false,
            ])
            ->add('password', TextType::class,[
                'attr'      => ['class' => 'pass', 'placeholder' => 'Password'],
                'required'  =>false,
            ])
            ->add('email', EmailType::class,[
                'attr'      => ['class' => 'email', 'placeholder' => 'Email'],
                'required'  =>false,
            ])
            ->add('abteilung', TextType::class,[
                'attr'      => ['class' => 'user_abteilung', 'placeholder' => 'Abteilung'],
                'required'  =>false,
            ])
            ->add('zusaetzlich', TextType::class,[
                'attr'      => ['class' => 'zusaetzlich_info', 'placeholder' => 'Info'],
                'required'  =>false,])
            ->add('signup', SubmitType::class,['label'=>'Signup']);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
            'csrf_protection' => true, // Standardmäßig true, aber zur Sicherheit hier hinzufügen
            'csrf_field_name' => '_token', // Der Name des CSRF-Feldes
            'csrf_token_id' => 'user', // Ein eindeutiger Bezeichner für das Token
        ]);
    }

}
